VAR_HEIGHT_DELIMITER = '|'
TAB_PREFIX_DYNAMIC = '-'
TAB_PREFIX_INPUT = '_'
COL_DELIMITER = ':'
FRIENDLY_NAME_DELIMITER = ':'
VAR_SUMMARY_METHOD_DELIMITER = ':'

TAB_TITLE_STEPS = '_steps'
TAB_TITLE_SUMMARY = '_summary'

GROUP_INDENT = '    '